"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

images = ('img',
          ['./img/spacebg.jpg',
           './img/spaceship.png',
           './img/icon.icns',
           './img/warpgate.png'])

sfx = ('sfx',
       ['./sfx/BWOM.ogg',
        './sfx/rcs.ogg',
        './sfx/space_music_2.mp3'])

fonts = ('fonts',
         ['./fonts/BlackOpsOne.ttf',
          './fonts/Iceland.ttf'])

APP = ['spaceport.py']
DATA_FILES = [images, sfx, fonts]
OPTIONS = {'argv_emulation': False,
           'iconfile': './img/icon.icns',
           'excludes': ['OpenGL', 'numpy'],
           'plist': {'NSHumanReadableCopyright': u"Copyright © 2017 Lewis Porter"}
           }

setup(
    name='SPACEPORT',
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
